name: Verify format

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.17.3]
        otp: [26]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-format
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Install Mix dependencies
        run: mix deps.get
        if: steps.mix-cache-format.outputs.cache-hit != 'true' || steps.mix-cache-format.outputs.cache-hit == ''

      - name: Format
        run: mix format --check-formatted