jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.17.3]
        otp: [26]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v3
        id: mix-cache-coverage
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 15
          done
      - name: Install Mix dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix ecto.create      
      - name: Verify Coverage and tests
        run: mix coveralls.html
    services:
      postgres:
        image: postgres:17.4-alpine
        ports: ['5432:5432']
        env:    
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hello_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
